"""Initial migration

Revision ID: add59f727b41
Revises:
Create Date: 2025-10-12 14:41:58.997456

"""

from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "add59f727b41"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    userstatus_enum = sa.Enum(
        "ACTIVE", "INACTIVE", "SUSPENDED", "DELETED", name="userstatus"
    )
    userrole_enum = sa.Enum("USER", "ADMIN", name="userrole")
    # Create enum types if they don't already exist (safe for re-runs).
    userstatus_enum.create(bind, checkfirst=True)
    userrole_enum.create(bind, checkfirst=True)

    userstatus_enum_in_table = sa.Enum(
        "ACTIVE",
        "INACTIVE",
        "SUSPENDED",
        "DELETED",
        name="userstatus",
        create_type=False,
    )
    userrole_enum_in_table = sa.Enum("USER", "ADMIN", name="userrole", create_type=False)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "status",
            userstatus_enum_in_table,
            nullable=False,
        ),
        sa.Column("role", userrole_enum_in_table, nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "query_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("document_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_query_logs_document_id"), "query_logs", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_query_logs_session_id"), "query_logs", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_query_logs_timestamp"), "query_logs", ["timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_query_logs_user_id"), "query_logs", ["user_id"], unique=False
    )
    op.create_table(
        "user_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "document_id", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column(
            "filename", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("pages", sa.Integer(), nullable=False),
        sa.Column("upload_time", sa.DateTime(), nullable=False),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_documents_document_id"),
        "user_documents",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_documents_user_id"), "user_documents", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_documents_user_id"), table_name="user_documents")
    op.drop_index(op.f("ix_user_documents_document_id"), table_name="user_documents")
    op.drop_table("user_documents")
    op.drop_index(op.f("ix_query_logs_user_id"), table_name="query_logs")
    op.drop_index(op.f("ix_query_logs_timestamp"), table_name="query_logs")
    op.drop_index(op.f("ix_query_logs_session_id"), table_name="query_logs")
    op.drop_index(op.f("ix_query_logs_document_id"), table_name="query_logs")
    op.drop_table("query_logs")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    bind = op.get_bind()
    sa.Enum("USER", "ADMIN", name="userrole").drop(bind, checkfirst=True)
    sa.Enum(
        "ACTIVE", "INACTIVE", "SUSPENDED", "DELETED", name="userstatus"
    ).drop(bind, checkfirst=True)
    # ### end Alembic commands ###
